security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        api_key_user_provider:
            id: App\Security\ApiKeyUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/api
            stateless: true
            provider: api_key_user_provider
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\ApiKeyAuthenticator
    access_control: